apiVersion: v1
kind: Service
metadata:
  name: {{ template "custom-metrics.name" . }}
  labels:
    app: {{ template "custom-metrics.name" . }}
    chart: {{ template "custom-metrics.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 6443
    protocol: TCP
    name: https
  selector:
    app: {{ template "custom-metrics.name" . }}
    release: {{ .Release.Name }}
