repository: gcr.io/google_containers

addonName: ingress-nginx.addons.k8s.io

# if running with kops' dns-controller, control route53 records creation
# https://github.com/kubernetes/kops/tree/master/dns-controller
dns:
  configure: true
  # could be more than one, 
  # the syntax is a comma separated list of fully qualified domain names
  # below is an example, don't use it (like, ever)
  hosts: foo.example.com,bar.example.org
  type: external

backend:
  name: nginx-default-backend
  image: defaultbackend
  tag: "1.0"
  ports:
    service: 80
    container: 8080
  replicas: 2

nginx:
  name: ingress-nginx
  image: nginx-ingress-controller
  tag: "0.9.0-beta.11"
  ports:
    http: 80
    https: 443
  replicas: 3