apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.proxy.name }}
  labels:
    component: {{ .Values.proxy.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.proxy.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0%
  template:
    metadata:
      labels:
        component: {{ .Values.proxy.name }}
    spec:
      containers:
      - name: {{ .Values.proxy.name }}
        image: {{ .Values.proxy.image.repo }}/{{ .Values.proxy.image.name }}:{{ .Values.proxy.image.tag }}
        ports:
        - containerPort: {{ .Values.service.port }}
          protocol: TCP
        env:
        {{- range $key, $value := .Values.proxy.env }}
        - name: {{ $key | upper | replace "-" "_" | quote }}
          value: {{ $value | quote }}
        {{- end }}
        - name: "AWS_ACCESS_KEY_ID"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.proxy.secret }}
              key: access-key-id
        - name: "AWS_SECRET_ACCESS_KEY"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.proxy.secret }}
              key: secret-access-key