apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "fluent-bit.name" . }}
  labels:
    app: {{ template "fluent-bit.name" . }}
    component: logger
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/fluentbit-config.yaml") . | sha256sum }}
spec:
  selector:
    matchLabels:
      app: {{ template "fluent-bit.fullname" . }}
      component: logger
  template:
    metadata:
      labels:
        app: {{ template "fluent-bit.fullname" . }}
        component: logger
    spec:
      serviceAccountName: {{ template "fluent-bit.fullname" . }}
      containers:
      - name: {{ template "fluent-bit.name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.pullPolicy }}"
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: config
          mountPath: /fluent-bit/etc
      terminationGracePeriodSeconds: 10
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
    {{- end }}
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: config
        configMap:
          name: {{ template "fluent-bit.fullname" . }}-config
