apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    component: {{ .Values.service.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
  selector:
    component: {{ .Values.proxy.name }}