replicaCount: 1

image:
  repository: nuvo/kafka-manager
  tag: "v1"

service:
  name: kafka-manager
  port: 9000
  type: NodePort

env:
  ZK_HOSTS: "zookeeper:2181"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

