replicaCount: 1

image:
  repository: sheepkiller/kafka-manager
  tag: "1.3.1.8"

service:
  name: kafka-manager
  port: 9000
  type: LoadBalancer

env:
  ZK_HOSTS: "zookeeper:2181"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

