apiVersion: batch/v2alpha1 #for API server versions >= 1.8.0 use batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}" 
spec:
  schedule: {{ .Values.schedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.history.successfulJobs }}
  failedJobsHistoryLimit: {{ .Values.history.failedJobs }}
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 120
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: {{ .Values.image.name }}:{{ .Values.image.tag }}
            name: {{ .Chart.Name }}
            args: ["--config", "{{ .Values.mountPath }}/config.yml", "{{ .Values.mountPath }}/action_file.yml"]
            volumeMounts:
            - name: config
              mountPath: {{ .Values.mountPath }}
          volumes:
          - name: config
            configMap:
              name: {{ .Chart.Name }}-config
          restartPolicy: OnFailure