kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: {{ template "nginx-ingress.defaultBackend.fullname" . }}
  labels:
    app: {{ template "nginx-ingress.name" . }}
    component: {{ .Values.backend.name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    matchLabels:
      app: {{ template "nginx-ingress.name" . }}
      component: {{ .Values.backend.name }}
  strategy:
{{ toYaml .Values.updateStrategy | indent 4 }}
  template:
    metadata:
      labels:
        app: {{ template "nginx-ingress.name" . }}
        component: {{ .Values.backend.name }}
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: {{ .Values.backend.name }}
        image: "{{ .Values.backend.image.repository}}:{{ .Values.backend.image.tag}}"
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.backend.ports.container  }}
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        resources:
{{ toYaml .Values.backend.resources | indent 10}}
        ports:
        - name: http
          containerPort: {{ .Values.backend.ports.container  }}
          protocol: TCP
